"""add thread id to conversations

Revision ID: 6263a1f17a67
Revises: f98b1203083a
Create Date: 2026-08-17 12:27:09.664598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6263a1f17a67'
down_revision: Union[str, Sequence[str], None] = 'f98b1203083a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add the column temporarily as nullable
    op.add_column(
        "conversations",
        sa.Column(
            "thread_id",
            sa.String(length=100),
            nullable=True
        )
    )

    # 2. Generate a unique thread_id for existing conversations
    connection = op.get_bind()

    conversations = connection.execute(
        sa.text("SELECT id FROM conversations")
    ).fetchall()

    import uuid

    for conversation in conversations:
        connection.execute(
            sa.text(
                """
                UPDATE conversations
                SET thread_id = :thread_id
                WHERE id = :id
                """
            ),
            {
                "id": conversation.id,
                "thread_id": str(uuid.uuid4())
            }
        )

    # 3. Make the column required
    op.alter_column(
        "conversations",
        "thread_id",
        nullable=False
    )

    # 4. Add the unique index
    op.create_index(
        op.f("ix_conversations_thread_id"),
        "conversations",
        ["thread_id"],
        unique=True
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_thread_id'), table_name='conversations')
    op.drop_column('conversations', 'thread_id')
    # ### end Alembic commands ###
