"""add unique constraint to file_hash

Revision ID: a3b8c1d2e4f5
Revises: e1fbfecee257
Create Date: 2026-09-10 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b8c1d2e4f5'
down_revision: Union[str, Sequence[str], None] = 'e1fbfecee257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add unique constraint to file_hash column.

    IMPORTANT: Before running this migration, check for duplicate file_hash values:

        SELECT file_hash, COUNT(*)
        FROM academic_documents
        GROUP BY file_hash
        HAVING COUNT(*) > 1;

    If duplicates exist, resolve them before applying this migration.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_documents_file_hash'), table_name='academic_documents')
    op.create_index(op.f('ix_academic_documents_file_hash'), 'academic_documents', ['file_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Remove unique constraint from file_hash, restore non-unique index."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_documents_file_hash'), table_name='academic_documents')
    op.create_index(op.f('ix_academic_documents_file_hash'), 'academic_documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###
