"""add academic documents

Revision ID: e1fbfecee257
Revises: 6263a1f17a67
Create Date: 2026-08-17 19:49:45.411792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1fbfecee257'
down_revision: Union[str, Sequence[str], None] = '6263a1f17a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('college', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_documents_file_hash'), 'academic_documents', ['file_hash'], unique=False)
    op.create_index(op.f('ix_academic_documents_id'), 'academic_documents', ['id'], unique=False)
    op.create_index(op.f('ix_academic_documents_user_id'), 'academic_documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_documents_user_id'), table_name='academic_documents')
    op.drop_index(op.f('ix_academic_documents_id'), table_name='academic_documents')
    op.drop_index(op.f('ix_academic_documents_file_hash'), table_name='academic_documents')
    op.drop_table('academic_documents')
    # ### end Alembic commands ###
